"""Guard the README's figures.

The figures are committed PNGs generated by ``scripts/capture_docs_images.py``,
which needs a browser binary and therefore never runs in CI. Nothing else would
notice a renamed file or a half-written capture, so these tests do: a broken
image on the front page of the project is the most visible bug we can ship.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
README = ROOT / "README.md"
IMAGES = ROOT / "docs" / "images"

# Matches both the <picture>/<source srcset=...> and <img src=...> forms, and
# keeps only the repo-relative tail: the README uses absolute raw.githubusercontent
# URLs so the figures also render on the PyPI project page, which does not resolve
# relative paths.
REFERENCE = re.compile(r"(?:src|srcset)=\"[^\"]*?(docs/images/[^\"]+)\"")


def _referenced() -> set[str]:
    return set(REFERENCE.findall(README.read_text(encoding="utf-8")))


def test_readme_references_at_least_one_figure() -> None:
    """A README with no figures means the capture pipeline lost its only consumer."""
    assert _referenced(), "README references no docs/images figure"


def test_every_referenced_image_exists_and_is_non_empty() -> None:
    """A truncated capture still writes a file, so size is part of the check."""
    for reference in sorted(_referenced()):
        path = ROOT / reference
        assert path.is_file(), f"{reference} is referenced by README.md but missing"
        assert path.stat().st_size > 0, f"{reference} is empty"


def test_every_light_figure_has_a_dark_twin() -> None:
    """GitHub serves the dark source to dark-mode readers; a missing twin is invisible locally."""
    for light in sorted(IMAGES.glob("*-light.png")):
        dark = light.with_name(light.name.replace("-light.png", "-dark.png"))
        assert dark.is_file(), f"{light.name} has no dark counterpart"


def test_no_orphaned_images() -> None:
    """Unreferenced PNGs are dead weight in the repository and go stale silently."""
    referenced = {(ROOT / r).resolve() for r in _referenced()}
    orphans = sorted(p.name for p in IMAGES.glob("*.png") if p.resolve() not in referenced)
    assert not orphans, f"docs/images contains unreferenced files: {', '.join(orphans)}"
